import { motion } from 'framer-motion';
import { BarChart3, Shield, Cpu, Lock, Zap, AlertCircle, TrendingDown, Users } from 'lucide-react';

const nodeTypes = [
  {
    icon: <Shield size={22} />,
    title: 'Validator Nodes',
    role: 'Consensus Security',
    stake: '$WAVE only — $100,000 USD fiat-pegged minimum (oracle-adjusted)',
    yield: '8–9 bps of global network settlement volume',
    mechanism: 'Staked $WAVE is locked in Dynamic Threshold Committees (DTC). Committee aggregate stake always exceeds the fiat value of validated blocks at a 150% safety margin.',
    badge: 'Security Layer',
    color: 'var(--teal-400)',
  },
  {
    icon: <Zap size={22} />,
    title: 'Facilitator Nodes',
    role: 'Gas Abstraction as a Service (GAaaS)',
    stake: 'Dual-Asset SLA Bond: $WAVE base + optional USDC/USDT for routing bandwidth. Tier 1: 10,000 $WAVE · Tier 2: 100,000 $WAVE',
    yield: '1–3 bps micro-spread on specific transaction volume routed and sponsored',
    mechanism: 'Gas fronted by the Facilitator is atomically reimbursed in the same block from the Client Application\'s on-chain Paymaster contract — zero counterparty risk.',
    badge: 'Liquidity Layer',
    color: '#60A5FA',
  },
  {
    icon: <Lock size={22} />,
    title: 'Archive Nodes',
    role: 'SEC 17a-4 WORM Compliance',
    stake: 'None required',
    yield: '0 bps — passive read-only compliance infrastructure',
    mechanism: 'Archive nodes pipe network state into software-defined WORM storage (e.g., AWS S3) for institutional legal and risk officers. They do not participate in consensus.',
    badge: 'Compliance Layer',
    color: 'var(--accent-amber)',
  },
];

const distribution = [
  { label: 'Validator Nodes', bps: '8–9 bps', pct: '57%', color: 'var(--teal-400)', desc: 'Core consensus security' },
  { label: 'Facilitator Nodes', bps: '1–3 bps', pct: '13%', color: '#60A5FA', desc: 'Gas abstraction routing' },
  { label: 'Protocol Treasury', bps: '3–4 bps', pct: '27%', color: 'var(--accent-amber)', desc: 'Maintenance, audits, governance' },
];

const supply = [
  { label: 'DEX Circulating Supply', value: '2,000,000 $WAVE', sub: 'Paired with $2M USDC at $1.00 Day-1 price', color: 'var(--teal-400)' },
  { label: 'Enterprise Reserve', value: '998,000,000 $WAVE', sub: 'OTC only — time-locked into staking contracts', color: '#60A5FA' },
];

const allocation = [
  { label: 'Enterprise Reserve & Ecosystem', pct: '65%', detail: 'Network security grants, OTC distribution to institutional operators (12–24 month staking lock-ups)' },
  { label: 'Core Team & Foundation', pct: '20%', detail: '1-year cliff · 48-month linear vesting' },
  { label: 'Seed & Strategic Investors', pct: '15%', detail: '1-year cliff · 24-month linear vesting' },
];

export default function ProtocolEconomics() {
  return (
    <div className="container section">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
        <span className="section-label">Governance / Protocol Economics</span>
        <h1>Real Yield <span style={{ color: 'var(--teal-400)' }}>Tokenomics</span></h1>
        <p style={{ maxWidth: 680, marginTop: 12, marginBottom: 16 }}>
          Every yield generated by WaveCollapse network nodes is backed by a single deterministic cash flow:
          a <strong>15 basis point (bps) institutional settlement fee</strong> paid by Client Applications on every
          cleared transaction. No inflationary printing. No ponzinomics. Real cash flow from real institutional volume.
        </p>
        <div style={{ display: 'flex', gap: 12, marginBottom: 48, flexWrap: 'wrap' }}>
          <span className="badge badge-teal">$WAVE Native L1 Token</span>
          <span className="badge badge-blue">Fixed Supply · 1B Total</span>
          <span className="badge badge-amber">Zero Inflationary Rewards</span>
        </div>

        {/* ── Regulatory Notice ── */}
        <div className="glass-card" style={{ padding: 20, marginBottom: 48, display: 'flex', gap: 14, alignItems: 'flex-start', borderColor: 'rgba(245,158,11,0.3)' }}>
          <AlertCircle size={18} color="var(--accent-amber)" style={{ flexShrink: 0, marginTop: 2 }} />
          <div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', fontWeight: 700, color: 'var(--accent-amber)', letterSpacing: '0.08em', marginBottom: 6 }}>
              REGULATORY CLASSIFICATION
            </div>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-tertiary)', lineHeight: 1.7 }}>
              <strong style={{ color: 'var(--text-secondary)' }}>$WAVE</strong> is a Layer 1 utility token used strictly for cryptoeconomic security (staking),
              liquidity routing (SLA bonds), and settlement fees. It is classified as a <strong style={{ color: 'var(--text-secondary)' }}>Digital Commodity</strong> under FIT21.
              The <strong style={{ color: 'var(--text-secondary)' }}>Protocol Treasury Restricted Utility Pool</strong> prohibits distributions as dividends,
              yield, or profit-sharing by smart contract — preserving compliance with the Howey Test.{' '}
              <strong style={{ color: 'var(--text-secondary)' }}>WAVE-S</strong> is a separate, protocol-level smart contract standard for SEC-regulated
              financial instruments (not a token). This document does not constitute an offer or solicitation for investment.
            </p>
          </div>
        </div>

        {/* ── Token Classification ── */}
        <h2 style={{ marginBottom: 20 }}>Token <span className="gradient-text">Classification Matrix</span></h2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 56 }}>
          <motion.div className="glass-card-teal" style={{ padding: 28 }}
            initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.4rem', fontWeight: 800, color: 'var(--teal-300)', marginBottom: 8 }}>$WAVE</div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem', color: 'var(--teal-400)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 14 }}>Native Layer 1 Asset · FIT21 Digital Commodity</div>
            <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              Decentralized endogenous utility token used strictly for:
            </p>
            <ul style={{ marginTop: 10, paddingLeft: 18, display: 'flex', flexDirection: 'column', gap: 6 }}>
              {['Cryptoeconomic security (Validator staking)', 'Liquidity routing (Facilitator SLA bonds)', 'Network settlement fee medium', 'Governance voting (Restricted Utility Pool)'].map(i => (
                <li key={i} style={{ fontSize: '0.82rem', color: 'var(--text-tertiary)' }}>{i}</li>
              ))}
            </ul>
          </motion.div>
          <motion.div className="glass-card" style={{ padding: 28, borderColor: 'rgba(96,165,250,0.3)' }}
            initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.08 }}>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.4rem', fontWeight: 800, color: '#93C5FD', marginBottom: 8 }}>WAVE-S</div>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem', color: '#60A5FA', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 14 }}>RWA Security Standard · Not a Token</div>
            <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              Protocol-level smart contract standard for SEC-regulated financial instruments. Includes built-in:
            </p>
            <ul style={{ marginTop: 10, paddingLeft: 18, display: 'flex', flexDirection: 'column', gap: 6 }}>
              {['KYC/AML whitelisting (programmable compliance hooks)', 'Forced clawbacks and transfer restrictions', 'Fractional real estate, private credit, tokenized treasuries', 'All compliance liability remains with Client Applications'].map(i => (
                <li key={i} style={{ fontSize: '0.82rem', color: 'var(--text-tertiary)' }}>{i}</li>
              ))}
            </ul>
          </motion.div>
        </div>

        {/* ── Node Architecture ── */}
        <h2 style={{ marginBottom: 20 }}>Node Architecture & <span className="gradient-text">Staking Mechanics</span></h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 20, marginBottom: 56 }}>
          {nodeTypes.map((n, i) => (
            <motion.div key={n.title} className="glass-card" style={{ padding: 28 }}
              initial={{ opacity: 0, x: -16 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ delay: i * 0.08 }}>
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: 20 }}>
                <div style={{ width: 48, height: 48, background: `${n.color}15`, border: `1px solid ${n.color}40`, borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', color: n.color, flexShrink: 0 }}>
                  {n.icon}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 6, flexWrap: 'wrap' }}>
                    <h3 style={{ fontSize: '1.05rem', margin: 0 }}>{n.title}</h3>
                    <span className="badge badge-teal" style={{ color: n.color, background: `${n.color}15`, borderColor: `${n.color}40` }}>{n.badge}</span>
                  </div>
                  <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.72rem', color: 'var(--text-tertiary)', marginBottom: 16, letterSpacing: '0.06em' }}>{n.role}</div>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 16 }}>
                    <div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.68rem', fontWeight: 700, color: 'var(--text-tertiary)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 5 }}>Staking Requirement</div>
                      <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.6 }}>{n.stake}</p>
                    </div>
                    <div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.68rem', fontWeight: 700, color: n.color, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 5 }}>Yield</div>
                      <p style={{ fontSize: '0.82rem', color: 'var(--text-primary)', lineHeight: 1.6, fontWeight: 600 }}>{n.yield}</p>
                    </div>
                    <div>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.68rem', fontWeight: 700, color: 'var(--text-tertiary)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 5 }}>Mechanism</div>
                      <p style={{ fontSize: '0.82rem', color: 'var(--text-tertiary)', lineHeight: 1.6 }}>{n.mechanism}</p>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* ── 15 bps Distribution ── */}
        <h2 style={{ marginBottom: 8 }}>15 bps Settlement <span className="gradient-text">Distribution Engine</span></h2>
        <p style={{ color: 'var(--text-tertiary)', fontSize: '0.875rem', marginBottom: 28 }}>
          Every transaction cleared on WaveCollapse L1 incurs a 15 bps fee programmatically routed to the three network pillars.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginBottom: 56 }}>
          {distribution.map((d, i) => (
            <motion.div key={d.label} className="glass-card" style={{ padding: 24, textAlign: 'center' }}
              initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }} transition={{ delay: i * 0.08 }}>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '2rem', fontWeight: 800, color: d.color, marginBottom: 6 }}>{d.bps}</div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', fontWeight: 700, color: d.color, marginBottom: 8 }}>{d.label}</div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-tertiary)' }}>{d.desc}</div>
            </motion.div>
          ))}
        </div>

        {/* ── Supply Structure ── */}
        <h2 style={{ marginBottom: 8 }}>Genesis Supply & <span className="gradient-text">Cryptoeconomic Distribution</span></h2>
        <p style={{ color: 'var(--text-tertiary)', fontSize: '0.875rem', marginBottom: 28 }}>
          Fixed deflationary supply. Zero inflationary block rewards. Structured to prevent retail market manipulation.
        </p>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, marginBottom: 32 }}>
          {supply.map((s, i) => (
            <motion.div key={s.label} className="glass-card" style={{ padding: 24 }}
              initial={{ opacity: 0, y: 16 }} whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }} transition={{ delay: i * 0.08 }}>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.1rem', fontWeight: 800, color: s.color, marginBottom: 6 }}>{s.value}</div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', fontWeight: 700, color: 'var(--text-secondary)', marginBottom: 6 }}>{s.label}</div>
              <div style={{ fontSize: '0.78rem', color: 'var(--text-tertiary)' }}>{s.sub}</div>
            </motion.div>
          ))}
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginBottom: 56 }}>
          {allocation.map((a, i) => (
            <div key={a.label} style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '14px 20px', background: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-subtle)', borderRadius: 10 }}>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.3rem', fontWeight: 800, background: 'var(--grad-teal)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', minWidth: 52 }}>{a.pct}</div>
              <div>
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.82rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: 3 }}>{a.label}</div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-tertiary)' }}>{a.detail}</div>
              </div>
            </div>
          ))}
        </div>

        {/* ── Deflationary Burn ── */}
        <div className="glass-card-teal" style={{ padding: 28, marginBottom: 32, display: 'flex', gap: 20, alignItems: 'flex-start' }}>
          <TrendingDown size={24} color="var(--teal-400)" style={{ flexShrink: 0, marginTop: 2 }} />
          <div>
            <h3 style={{ marginBottom: 8 }}>Deflationary Burn Mechanism</h3>
            <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
              100% of all slashed $WAVE tokens are <strong>permanently burned</strong> — never recycled into the Protocol Treasury.
              Every negligent or malicious operator removed from the network makes the remaining staked $WAVE mathematically scarcer,
              automatically rewarding good actors through the deflationary mechanic.
            </p>
          </div>
        </div>

        {/* ── Speculator Superpower ── */}
        <div className="glass-card" style={{ padding: 28, marginBottom: 32, display: 'flex', gap: 20, alignItems: 'flex-start', borderColor: 'rgba(96,165,250,0.3)' }}>
          <Shield size={24} color="#60A5FA" style={{ flexShrink: 0, marginTop: 2 }} />
          <div>
            <h3 style={{ marginBottom: 8 }}>The Speculator Superpower</h3>
            <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7, margin: 0 }}>
              Because node admission is fiat-pegged ($100,000 USD equivalent), volatility naturally serves as a security multiplier. 
              A 10x rise in $WAVE's speculative price means existing Dynamic Threshold Committees now inherently provide <strong>10x the security capacity</strong>{' '}
              for institutional asset transfers — with zero required capital influx from the foundation. Institutional capacity effortlessly scales with market speculation.
            </p>
          </div>
        </div>

        {/* ── OTC Desk CTA ── */}
        <div className="glass-card" style={{ padding: 28 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
            <Users size={20} color="var(--teal-400)" />
            <h3 style={{ margin: 0 }}>Institutional OTC Desk</h3>
          </div>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 20 }}>
            Institutions requiring significant $WAVE capital to spin up nodes do not source from the public DEX — which causes
            price slippage and destabilizes infrastructure access. Instead, operators sign an SLA with the WaveCollapse Foundation
            to purchase $WAVE over-the-counter. Tokens are cryptographically time-locked exclusively for node staking,
            preserving the fiat barrier-to-entry stability enforced by the oracle-pegged minimum.
          </p>
          <a href="/solutions/intake" className="btn-secondary" style={{ display: 'inline-flex' }} id="economics-otc-intake-cta">
            Apply for OTC Access
          </a>
        </div>
      </motion.div>
    </div>
  );
}
